import pygame

WINSIZE = [800, 480]
ROTATE90 = True
#FRAMERATE = None
FRAMERATE = 10
THREADED_SYSTEM = True
#MODE = pygame.NOFRAME | pygame.FULLSCREEN | pygame.DOUBLEBUF | pygame.HWSURFACE
MODE = pygame.DOUBLEBUF | pygame.HWSURFACE

BATT_DEVICE = '/sys/class/power_supply/bq27510-0/'
BATT_CAPACITY = 'capacity'
BATT_STATUS = 'status'
BATT_QUERY_TIME = 5

NETWORK_QUERY_TIME = 15

RESOURCE_DIR = '/home/clfs/nookui/res'

SYSTEM_HEADER_FONT_SIZE = 40
SYSTEM_HEADER_BAR_HEIGHT = 35
SYSTEM_HEADER_MEM_ICON = 'memory.png'
SYSTEM_HEADER_MEM_ICON_SIZE = (25,25)
SYSTEM_HEADER_CPU_ICON = 'cpu.png'
SYSTEM_HEADER_CPU_ICON_SIZE = (25,25)
SYSTEM_HEADER_BATT_ICON = 'battery.png'
SYSTEM_HEADER_BATT_ICON_SIZE = (25,25)
SYSTEM_HEADER_SPACING = 10

LAUNCHER_DIR = '/home/clfs/nookui/apps'
LAUNCHER_DEFAULT_CLASS = 'PygameApp'
LAUNCHER_ICON_FONT_SIZE = 24
LAUNCHER_ICON_IMAGE_SIZE = (64,64)
LAUNCHER_DEFAULT_ICON_IMAGE = 'python.png'
